import React, { useState, useEffect } from "react";

import { Loader, Card, FormFeild } from "../components";

const RenderCards = ({ data, title }) => {
  //Optional chaining simplifies this process. With optional chaining, if you try to access a property on an object that's null or undefined, instead of throwing an error, it simply returns undefined:
  if (data?.length > 0) {
    return data.map((post) => {
      <Card key={post._id} {...post} />;
    });
  }
  return (
    <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setsearchText] = useState();
  return (
    <section className="max-w-7xl mx-auto">
      {/* //Heading and paragraph */}
      <div>
        <h1 className="font-extrabold text-black text-[32px]">
          The community showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w[500px]">
          Browse through images generated by DALL-E
        </p>
      </div>
      {/* //Form */}
      <div className="mt-16">
        <FormFeild />
      </div>
      {/* //Cards*/}
      <div className="mt-10 ">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <div>
            {searchText && (
              <h2 className="font-medium text-[rgb(102,110,117)] text-xl mb-3">
                Showing results for{" "}
                <span className="text-[rgb(83,83,83)] font-bold">
                  {searchText}
                </span>
              </h2>
            )}
            <div className="gird lg:gir-cols-4 sm:gird-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards data={[]} title="no search results found" />
              ) : (
                <RenderCards data={[]} title="no posts found" />
              )}
            </div>
          </div>
        )}
      </div>
    </section>
  );
};

export default Home;
